// import { ReactComponent as Analytics } from "../assets/images/IntroPageImages/analytics 2.svg";
// import { ReactComponent as Campaign } from "../assets/images/IntroPageImages/campaign 2.svg";
// import { ReactComponent as Communities } from "../assets/images/IntroPageImages/communities 2.svg";
// import { ReactComponent as Conversation } from "../assets/images/IntroPageImages/conversation 2.svg";
// import { ReactComponent as CustomerReview } from "../assets/images/IntroPageImages/customer-review 2.svg";
// import { ReactComponent as PersonOne } from "../assets/images/IntroPageImages/Group 271-1.svg";
// import { ReactComponent as PersonTwo } from "../assets/images/IntroPageImages/Group 271.svg";
// import { ReactComponent as PersonThree } from "../assets/images/IntroPageImages/Group 272-1.svg";
// import { ReactComponent as Logo } from "../assets/images/IntroPageImages/logo 3.svg";
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';
// // import {ReactComponent as Analytics} from '../assets/images/IntroPageImages/analytics 2.svg';

// export const Analytics;
// export const Logo;
